apiVersion: v1
kind: Namespace
metadata:
  name: ca-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: injector
  namespace: ca-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-injector
  namespace: ca-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-injector
  template:
    metadata:
      labels:
        app: ca-injector
    spec:
      serviceAccount: injector
      containers:
      - name: ca-injector
        image: andrewstuart/ca-injector
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: cert
          mountPath: /cert
      volumes: 
      - name: cert
        secret:
          secretName: injector.ca-injector.svc.cluster.local.tls
---
apiVersion: v1
kind: Service
metadata:
  name: ca-injector
  namespace: ca-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: ca-injector
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-mwh-cert
  namespace: ca-injector
spec:
  secretName: injector.ca-injector.svc.cluster.local.tls
  dnsNames:
  - ca-injector.ca-injector.svc.cluster.local
  - ca-injector.ca-injector.svc
  issuerRef:
    name: vault # Replace this issuer with your own issuer
    kind: ClusterIssuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ca-injector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ca-injector-list-delete-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ca-injector
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:ca-injector:injector
